### ISSUE TITLE
[ feature request ] custom songs NOT FOR UPLOAD

### ISSUE THREAD

**Issue by gzhegow1991** [privateryann1/TarkovInstruments#1]
Please, take a look of Mordhau game.
There's music tools that could be played using numpad 0-9 keys or microphone input stream. Not sure its available in-game using typescript but its really fun to connect AIMP to input device, and start to play midi sound that is transformed to the song.

**Comment by privateryann1** [comment]
I definitely would like to achieve this eventually. My idea from the start was to do that, but I wanted to start off simple and get something working.

**Comment by gzhegow1991** [comment]
n1

Will you make additional mods? Bots behaviors needs to simplification. I mean fight is good after SAIN, but walking map is disabled or bad.

**Comment by privateryann1** [comment]
Yeah I plan to work on more mods that involve animating and importing assets through Unity, like more instruments, food items, that kind of stuff. I'm not skilled enough to create a mod such as SAIN, and there's already some really great people who have all that covered.

**Comment by privateryann1** [comment]
Feature has been implemented in [v1.1.0](https://github.com/privateryann1/TarkovInstruments/releases/tag/v1.1.0)
